apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-kubernetes
  labels:
    app: jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: docker.io/yash012/jenkins:latest
        ports:
        - containerPort: 8080
